// Generated by https://quicktype.io

export interface PO {
  id?: number;
  service_name: string;
  service_version: string;
  request_date: string;
  issue_date?: string;
  expiration_date?: string;
  issuer?: string;
  id_PO: string;
  status: Status;
  image: string;
  name_organization: string;
  address_organization: string;
  ISO_Country_Code: string;
  url_organization: string;
  email_organization: string;
  files?: File[];
}

interface Status {
  in_progress: string;
  rejected: string;
  validated: string;
  expired: string;
}

interface File {
  name: string;
  size: number;
  type: string;
  data: Blob;
}
