// Generated by https://quicktype.io

export interface PO {
  id: number;
  service_name: string;
  id_PO: string;
  status: Status;
  date: string;
  image: string;
  name_organization: string;
  address_organization: string;
  ISO_Country_Code: string;
  url_organization: string;
  email_organization: string;
}

interface Status {
  in_progress: string;
  rejected: string;
  validated: string;
}
